server:
  port: 8787
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/demo_employee?useSSL=false&useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&allowPublicKeyRetrieval=true&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*/*Mapper.xml
  type-aliases-package: com.vector.demo.bean

